---
title: Rapidly increasing cases
author: Yea-Hung Chen
date: '2020-11-19'
slug: []
categories: []
tags: []
weight: 2
---

```{r,setup,include=FALSE}
knitr::opts_knit$set(root.dir='../../r/')
```

```{r,echo=FALSE,warning=FALSE,results='asis'}
source('plot time series.r')
geography<-'county'
rising.counties<-readRDS('rising_counties.rds')
plot_time_series(rising.counties[1])
plot_time_series(rising.counties[2]) 
plot_time_series(rising.counties[3]) 
plot_time_series(rising.counties[4]) 
plot_time_series(rising.counties[5]) 
plot_time_series(rising.counties[6])
plot_time_series(rising.counties[7]) 
plot_time_series(rising.counties[8]) 
plot_time_series(rising.counties[9]) 
plot_time_series(rising.counties[10])
plot_time_series(rising.counties[11]) 
plot_time_series(rising.counties[12]) 
plot_time_series(rising.counties[13]) 
plot_time_series(rising.counties[14]) 
plot_time_series(rising.counties[15]) 
plot_time_series(rising.counties[16]) 
plot_time_series(rising.counties[17]) 
plot_time_series(rising.counties[18]) 
plot_time_series(rising.counties[19]) 
plot_time_series(rising.counties[20]) 
```